name: Update MSYS2

on: [push, pull_request]

jobs:
  build:
    name: >-
      MSYS2 Update
    runs-on: 'windows-latest'
    strategy:
      fail-fast: false
      matrix:
        msystem: [ MINGW64, MINGW32 ]
    env:
      MSYSTEM: ${{ matrix.msystem }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update MSYS2
        run:  ./update_msys2.ps1
